#!/usr/bin/python

import requests

url = "http://192.168.0.102/?command=dataquery&uri=dl:SOIL_MET&format=json&mode=most-recent&p1"

response = requests.get(url) # bring the above url in to play
print response.content # return json
